services:
  app:
    build: .
    command: npm run start:dev
    ports:
      - '3000:3000'
    env_file:
      - .env
    depends_on:
      - postgres
      - kafka

  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: fantasy_league
      POSTGRES_USER: fantasy
      POSTGRES_PASSWORD: fantasy
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data

  kafka:
    image: bitnamilegacy/kafka:latest
    environment:
      KAFKA_CFG_NODE_ID: 1
      KAFKA_CFG_PROCESS_ROLES: broker,controller
      KAFKA_CFG_CONTROLLER_LISTENER_NAMES: CONTROLLER
      KAFKA_CFG_LISTENERS: INTERNAL://:9093,EXTERNAL://:9092,CONTROLLER://:9094
      KAFKA_CFG_ADVERTISED_LISTENERS: INTERNAL://kafka:9093,EXTERNAL://localhost:9092
      KAFKA_CFG_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT,CONTROLLER:PLAINTEXT
      KAFKA_CFG_CONTROLLER_QUORUM_VOTERS: 1@kafka:9094
      KAFKA_CFG_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: 'true'
      ALLOW_PLAINTEXT_LISTENER: 'yes'
    ports:
      - '9092:9092'

  kafka-ui:
    image: provectuslabs/kafka-ui:latest
    depends_on:
      - kafka
    environment:
      KAFKA_CLUSTERS_0_NAME: local
      KAFKA_CLUSTERS_0_BOOTSTRAPSERVERS: kafka:9093
    ports:
      - '8080:8080'

volumes:
  postgres-data:
